### ISSUE TITLE
steam_id_64 field from api/get_vip_ids contains player name, not steam ID

### ISSUE THREAD

**Issue by tunacado** [MarechJ/hll_rcon_tool#248]
I am working with a legacy database so this could be an artifact from a prior issue or input.

It appears possible, at least for the `get_vip_ids` API endpoint for the `steam_id_64` returned to be a player's name instead.

Simple reproducer script is like so:
```python
import requests

RCON_URL = 'https://my_cool_rcon:9999'
USERNAME = 'username'
PASSWORD = 'password'

session = requests.session()
response = session.get(
    '%s/api/login' % (RCON_URL),
    json={
        'username': USERNAME,
        'password': PASSWORD,
    },
)
result = response.json()

if result['failed'] is False:
    with session.get(
        '%s/api/get_vip_ids' % (RCON_URL)
    ) as result:
        vip_response = result.json()
        vip_list = vip_response['result']
        for vip in vip_list:
            print(vip)
```
In the returned lines for each VIP, there is one entry that has the `steam_id_64` as the player name:

```bash
{'steam_id_64': 'PlayerNameHere', 'name': 'PlayerNameHere', 'vip_expiration': None}
```

Of note is the player has `NoneType` as their `vip_expiration` but was still returned in the list (all other entries has valid `vip_expiration` fields), so we probably need to create something to sanitize the output regardless of how this was introduced.

I am working on trying to track down what is adding this to the returned response from within the JSON reply and will let you know if I find anything.

**Comment by tunacado** [comment]
Am I reading this right that `get vipids` is sent directly to the HLL server for this field to be stored there, and not internally in the RCON?

https://github.com/MarechJ/hll_rcon_tool/blob/master/rcon/commands.py#L446-L460

So this isn't storage in the RCON that is incorrect, it's actually stored within the HLL server this way, and *that* should have sanitized the input for us and theoretically that should have not have accepted this string value?

It could still have been an input issue in the CSV/VIP addition at some point for the `steam_64_id` but I suppose I expected the HLL server to do a check for the proper steam ID in the list, or at least verify it's numerical.

**Comment by tunacado** [comment]
Yes, I'd be willing to bet, either through user error or a prior RCON issue, the name was input wrong and the gameserver doesn't do input sanitization.

https://github.com/MarechJ/hll_rcon_tool/blob/master/rcon/commands.py#L635-L637

Other than input sanitization for these fields on the RCON side I'm not sure what we can do about it.  Where would we report game server bugs?  I'd be happy to file it (with hope that Team17 would include it in their QOL and eventual server patches) and report back if anyone looking at this agrees/directs me.

**Comment by timraay** [comment]
Can confirm that the game server does not validate steam IDs when adding a VIP. Same thing for adding Admin roles.

The response you got is actually coming from `rcon.extended_commands`, which inherits from `rcon.commands`. As you said, VIPs are ultimately stored by the game server. It does not support expiring VIPs though, which is an extra layer that we built on top, which does require VIPs to also be saved by us. `expiration_time` being `None` isn't unexpected - in fact it is the default.

You can discard any VIPs that don't have a proper steam ID, since they won't work anyway. Also, maybe it'd be smart to track down what's adding them 😛

You can file a bug report to T17 as well, if you want. The names of commands in question are `VipAdd` and `AdminAdd`. I'll also mention the issue on our [RCON Wishlist doc](https://gist.github.com/timraay/0782a9e8882cb185084a843fc8eea77d), which _supposedly_ the devs do read occasionally...

**Comment by tunacado** [comment]
Can confirm through REPL or the console that this does indeed do exactly as @timraay says, the actual gameserver doesn't perform verification.  So definitely not a CRCON issue, unless we want to pursue sanitation for consumers of the API, which in and of itself sounds like a larger project.

Unfortunately for my use case, I have no idea where the input of the name came from; it could have been done manually before I was involved with the game for all I know.

Talked in the discord a bit, going to see if we can follow up with T17, etc.  TYVM for the help.
