### ISSUE TITLE
Blacklist / Bans with arbitrary times

### ISSUE THREAD

**Issue by MarechJ** [MarechJ/hll_rcon_tool#42]
Add a way to apply a perma ban for an arbitrary time and a blacklist as well (from the moment it triggered)

Several ways to implement that, can discuss it on discord.

This is mostly python, also need to add a button + input for it

**Comment by FlorisE** [comment]
I had this implemented at one point but didn't commit it because we couldn't agree on using kicks, temp bans or perma bans for enforcing this. What do you think would be the best approach?
* Auto kick while being blacklisted for specific time
* Auto renew temp ban as long as player is blacklisted for specific time
* Perm ban but automatically remove after time expired
* Something else?

Auto kicks work universally, but will feel weird when rejoining and getting directly kicked, players also take up a slot while connecting. Perm ban gives mixed signals (you are permanently banned but the ban will expire). Temp bans might be worst (you are banned for 2 hours, just kidding, you are banned for X time).

**Comment by walgarch** [comment]
I think an autokick might make the most sense. That way the kick reason could be updated with the time remaining on the ban. I'm not sure any other method allows for time remaining to be sent.

**Comment by MarechJ** [comment]
The developers added that feature directly in the game API. It has a caveat when used on a player not in game anymore though. The reason won't be displayed to him when it tries to join again.
