### ISSUE TITLE
Improve Versioning and Releases

### ISSUE THREAD

**Issue by jordantrizz** [MarechJ/hll_rcon_tool#504]
Just some suggestions

1. Adding the file VERSION to the repository so that it's easy to identify the version.
This would help with support requests for the less technical both using git clone and zip installs.

2. The branch master should be renamed to main and set to the primary branch (optional, don't care ;)

3. Look at using git flow workflow https://www.youtube.com/watch?v=rX80eKPdA28 
This might not be ideal, trunk based workflow seems to be working great. But again, for the less technical, git pull is going to bring down commits and not releases.

**Comment by cemathey** [comment]
I might be a bit spoiled because my shell shows me the git branch that I'm on, I'm not super opposed to adding a VERSION file but that's just one more thing that we have to remember to manually update so I'd prefer not to.

Currently when the frontend image is built the tag version is [baked into the image](https://github.com/MarechJ/hll_rcon_tool/blob/66005d7be09da0b9dc07b2f329ab9ad271c40c9d/Dockerfile-frontend#L19) and it's shown in the UI (very bottom) and the tag is [also available as an endpoint](https://github.com/MarechJ/hll_rcon_tool/blob/66005d7be09da0b9dc07b2f329ab9ad271c40c9d/rconweb/api/views.py#L119)

I'm partial to these two methods since it's automatic.

I don't have opinions on git flow but I'm a total amateur, I'm not really inherently opposed to doing anything but our current process is `master` exists and stuff gets merged into it from different branches and when we're ready to do a release we tag `master` and then that exists forever as a snapshot in time. I watched that video but it seemed like basically the same thing but with extra steps?

**Comment by jordantrizz** [comment]
With your docker work this won't matter closing :)
